using FileHelpers;

namespace TestApplication.DataModels
{
    [IgnoreFirst(1)]
    [DelimitedRecord(",")]
    class DraftPersonalRecord
    {
        public int PlayerId { get; set; }
        public bool Interviewed { get; set; }

        public int LowScreenPasses { get; set; }
        public int LowShortPasses { get; set; }
        public int LowMediumPasses { get; set; }
        public int LowLongPasses { get; set; }
        public int LowDeepPasses { get; set; }
        public int LowThirdDown { get; set; }
        public int LowRunFrequency { get; set; }
        public int LowFuture1 { get; set; }
        public int LowAccuracy { get; set; }
        public int LowTiming { get; set; }
        public int LowSenseRush { get; set; }
        public int LowReadDefense { get; set; }
        public int LowTwoMinuteOffense { get; set; }
        public int LowFuture2 { get; set; }
        public int LowFuture3 { get; set; }
        public int LowFuture4 { get; set; }
        public int LowFuture5 { get; set; }
        public int LowFuture6 { get; set; }
        public int LowSpeed { get; set; }
        public int LowPowerInside { get; set; }
        public int LowThirdDownRuns { get; set; }
        public int LowHoleRecognition { get; set; }
        public int LowElusiveness { get; set; }
        public int LowSpeedOutside { get; set; }
        public int LowBlitzPickup { get; set; }
        public int LowAvoidDrops { get; set; }
        public int LowGetDownfield { get; set; }
        public int LowRouteRunning { get; set; }
        public int LowThirdDownReceiving { get; set; }
        public int LowBigPlayReceiving { get; set; }
        public int LowCourage { get; set; }
        public int LowAdjustToBall { get; set; }
        public int LowPuntReturns { get; set; }
        public int LowKickReturns { get; set; }
        public int LowFuture7 { get; set; }
        public int LowRunBlocking { get; set; }
        public int LowPassBlocking { get; set; }
        public int LowBlockStrength { get; set; }
        public int LowPuntingPower { get; set; }
        public int LowHangTime { get; set; }
        public int LowDirectionalPunting { get; set; }
        public int LowKickoffDistance { get; set; }
        public int LowKickoffHangTime { get; set; }
        public int LowKickingAccuracy { get; set; }
        public int LowKickingPower { get; set; }
        public int LowRunDefense { get; set; }
        public int LowPassRushTechnique { get; set; }
        public int LowManToManDefense { get; set; }
        public int LowZoneDefense { get; set; }
        public int LowBumpAndRunDefense { get; set; }
        public int LowPassRushStrength { get; set; }
        public int LowPlayDiagnosis { get; set; }
        public int LowPunishingHitter { get; set; }
        public int LowIntercepting { get; set; }
        public int LowEndurance { get; set; }
        public int LowSpecialTeams { get; set; }
        public int LowLongSnapping { get; set; }
        public int LowKickHolding { get; set; }

        public int HighScreenPasses { get; set; }
        public int HighShortPasses { get; set; }
        public int HighMediumPasses { get; set; }
        public int HighLongPasses { get; set; }
        public int HighDeepPasses { get; set; }
        public int HighThirdDown { get; set; }
        public int HighRunFrequency { get; set; }
        public int HighFuture1 { get; set; }
        public int HighAccuracy { get; set; }
        public int HighTiming { get; set; }
        public int HighSenseRush { get; set; }
        public int HighReadDefense { get; set; }
        public int HighTwoMinuteOffense { get; set; }
        public int HighFuture2 { get; set; }
        public int HighFuture3 { get; set; }
        public int HighFuture4 { get; set; }
        public int HighFuture5 { get; set; }
        public int HighFuture6 { get; set; }
        public int HighSpeed { get; set; }
        public int HighPowerInside { get; set; }
        public int HighThirdDownRuns { get; set; }
        public int HighHoleRecognition { get; set; }
        public int HighElusiveness { get; set; }
        public int HighSpeedOutside { get; set; }
        public int HighBlitzPickup { get; set; }
        public int HighAvoidDrops { get; set; }
        public int HighGetDownfield { get; set; }
        public int HighRouteRunning { get; set; }
        public int HighThirdDownReceiving { get; set; }
        public int HighBigPlayReceiving { get; set; }
        public int HighCourage { get; set; }
        public int HighAdjustToBall { get; set; }
        public int HighPuntReturns { get; set; }
        public int HighKickReturns { get; set; }
        public int HighFuture7 { get; set; }
        public int HighRunBlocking { get; set; }
        public int HighPassBlocking { get; set; }
        public int HighBlockStrength { get; set; }
        public int HighPuntingPower { get; set; }
        public int HighHangTime { get; set; }
        public int HighDirectionalPunting { get; set; }
        public int HighKickoffDistance { get; set; }
        public int HighKickoffHangTime { get; set; }
        public int HighKickingAccuracy { get; set; }
        public int HighKickingPower { get; set; }
        public int HighRunDefense { get; set; }
        public int HighPassRushTechnique { get; set; }
        public int HighManToManDefense { get; set; }
        public int HighZoneDefense { get; set; }
        public int HighBumpAndRunDefense { get; set; }
        public int HighPassRushStrength { get; set; }
        public int HighPlayDiagnosis { get; set; }
        public int HighPunishingHitter { get; set; }
        public int HighIntercepting { get; set; }
        public int HighEndurance { get; set; }
        public int HighSpecialTeams { get; set; }
        public int HighLongSnapping { get; set; }
        public int HighKickHolding { get; set; }
    }
}
